name: Terraform Apply

on:
  pull_request:
    types: [closed]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ inputs.github_ref }}
        run: |
          echo $GITHUB_REF
          echo $GITHUB_BASE_REF
          echo $GITHUB_HEAD_REF
          echo $GITHUB_REF_NAME	
          echo $GITHUB_WORKFLOW_REF
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        uses: ./.github/apply
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cli-config-credentials-token: ${{ secrets.TF_API_TOKEN }}
          terraform_directory: "tf"
          github_token: ${{ secrets.ACTIONS_SECRET }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}