name: Terraform Run Tests and Deploy

on:
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "rodrigo-curiel-org"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "TranscriptAI"
  CONFIG_DIRECTORY: "./tf"
jobs:
  terraform:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Interact with Terraform
        run: terraform --version

      - name: Terraform Init
        id: init
        run: terraform -chdir=./tf init
      
      - name: Terraform Plan
        id: plan
        run: terraform -chdir=./tf plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1